#!/bin/bash

helpFunction()
{
   echo ""
   echo "Usage: PRIMSeqTools"
   echo -e "\t-a String, Path to read1 fastq file, required"
   echo -e "\t-b String, Path to read2 fastq file, required"
   echo -e "\t-o String, Path to output directory, required"
   echo -e "\t-i String, Path to bwa index of target transcriptome, required"
   echo -e "\t-g String, Path to transcript,gene and gene type dictionary file in csv format, required" 
   echo -e "\t-l String, Path to the directory of lists of library and molecule barcodes, required"
   echo -e "\t-j String, Job ID to be prepended to the output files and directories, optional, default=SMOPINseq"
   echo -e "\t-t Int, Number of working threads, optional, default=2"
   echo -e "\t-r Char (T or F), remove intermediate files or not, optional, default=T" 
   echo -e "\t-h Print usage message" 
   echo 
   exit 1 # Exit script after printing help
}

while getopts "a:b:t:o:i:h:r:p:d:c:g:j:l:" opt
do
   case "$opt" in
      a ) read1="$OPTARG" ;;
      b ) read2="$OPTARG" ;;
      t ) numT="$OPTARG" ;;
      o ) outputDir="$OPTARG" ;;
      i ) bwaIndex="$OPTARG" ;;
      r ) removeFlag="$OPTARG" ;;
      g ) geneDic="$OPTARG" ;;
      j ) jobId="$OPTARG" ;;
      l ) bcDir="$OPTARG" ;;
      h ) helpFunction ;;
      ? ) helpFunction ;; # Print helpFunction in case parameter is non-existent
   esac
done

# Print helpFunction in case parameters are empty
if [ -z "$read1" ] || [ -z "$read2" ]
then
   echo "read1 or read2 missing";
   helpFunction
fi

if [ -z "$bwaIndex" ]
then
   echo "bwa index file missing";
   helpFunction
fi

if [ -z "$outputDir" ]
then
   echo "ouput directory missing";
   helpFunction
fi

if [ -z "$geneDic" ]
then
   echo "transcript gene dictionary file missing";
   helpFunction
fi

if [ -z "$bcDir" ]
then
   echo "library and molecule barcode directory missing";
   helpFunction
fi

if [ -z "$numT" ]
then
    numT=4
fi
wait

if [ -z "$removeFlag" ]
then
    removeFlag='T'
fi
wait

if [ ! -z "$jobId" ]
then
    jobId=${jobId}_
else
    jobId=SMONPINseq_
fi
wait


mkdir $outputDir
mkdir $outputDir/${jobId}processedFastq
mkdir $outputDir/${jobId}readId_UMI
mkdir $outputDir/${jobId}intermediateFiles
mkdir $outputDir/${jobId}alignment/
wait

python getCurrentDateTime.py $outputDir $jobId
wait

cat $outputDir/${jobId}intermediateFiles/runStart.txt > $outputDir/${jobId}SMOPIN_interactions.csv
cat $outputDir/${jobId}intermediateFiles/runStart.txt > $outputDir/${jobId}errorLog.txt 
wait

#map and sort
python lib_drug_Barcode_sort_SMOPIN.py $bcDir $read1 $read2 $outputDir $jobId 2>> $outputDir/${jobId}errorLog.txt

#write
python writeProteinEndReads.py $outputDir $jobId $read1 $read2 2>> $outputDir/${jobId}errorLog.txt

#trim
cutadapt -a CCCTCCAGTGAAGC -O 12  $outputDir/${jobId}processedFastq/proteinEnd.fastq > $outputDir/${jobId}processedFastq/proteinEnd.cut.fastq

fastp -i $outputDir/${jobId}processedFastq/proteinEnd.cut.fastq -o .$outputDir/${jobId}processedFastq/proteinEnd.cut.fastp.fastq -h $outputDir/${jobId}intermediateFiles/fastp.html -j $outputDir/${jobId}intermediateFiles/fastp.json


#map
source=$outputDir/${jobId}processedFastq
target=$outputDir/${jobId}alignment
half=$((numT/2))

bwa mem -v 1 -t $half $bwaIndex $source/proteinEnd.cut.fastp.fastq > $target/alignment.sam 2>> $outputDir/${jobId}errorLog.txt

samtools view -H $target/alignment.sam > $target/header.sam 2>> $outputDir/${jobId}errorLog.txt

samtools view -F 4 $target/alignment.sam | cat $target/header.sam - | samtools view -b - > $target/mapped.bam 2>> $outputDir/${jobId}errorLog.txt

samtools sort -n -@ $numT -o $target/mapped.sorted.bam $target/mapped.bam 2>> $outputDir/${jobId}errorLog.txt

bedtools bamtobed -cigar -i $target/mapped.sorted.bam > $target/mapped.sorted.bed 2>> $outputDir/${jobId}errorLog.txt

#write pairs
python writeDPIreads.py $bcDir $geneDic $outputDir $jobId 2>> $outputDir/${jobId}errorLog.txt


if [ $removeFlag == 'T' ]
then
    rm -r $outputDir/${jobId}intermediateFiles
    rm -r $outputDir/${jobId}processedFastq
fi
